#!/usr/bin/env node
/**
 * Writes a justified ignore file covering every actionable finding in a report.
 *
 * The end-to-end test needs to prove that suppression turns a failing scan into
 * a passing one. Hard-coding the identifiers would make the test break whenever
 * a scanner adds a rule or an advisory is published, so the ignore file is
 * derived from the first run's report instead.
 *
 * Usage: generate-ignores.mjs <report.json> <output.yml>
 */

import fs from 'node:fs';

const [reportPath, outputPath] = process.argv.slice(2);
if (!reportPath || !outputPath) {
  console.error('usage: generate-ignores.mjs <report.json> <output.yml>');
  process.exit(2);
}

const report = JSON.parse(fs.readFileSync(reportPath, 'utf8'));
const actionable = report.findings.filter((f) => !f.ignored && !f.belowThreshold);

// One entry per distinct id: a finding merged from several scanners is covered
// by a single `scanner: any` entry, which is what a real consumer would write.
const seen = new Set();
const entries = [];
for (const finding of actionable) {
  if (seen.has(finding.id)) continue;
  seen.add(finding.id);
  entries.push(finding);
}

const expires = new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10);

const quote = (value) => `"${String(value).replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;

const lines = [
  '# Generated by tests/e2e/generate-ignores.mjs for the end-to-end workflow.',
  '# Every entry carries a justification, because the Action rejects any that',
  '# does not -- including these.',
  'version: 1',
  '',
  'ignores:',
];

for (const finding of entries) {
  lines.push(`  - id: ${quote(finding.id)}`);
  lines.push('    scanner: any');
  lines.push(
    `    reason: ${quote(`End-to-end test fixture: this finding is planted deliberately by tests/e2e/build-fixture.sh to verify that justified suppression works (${finding.category}).`)}`,
  );
  lines.push(`    expires: ${quote(expires)}`);
  lines.push('');
}

fs.writeFileSync(outputPath, `${lines.join('\n').trimEnd()}\n`, 'utf8');

console.log(`wrote ${entries.length} justified entries to ${outputPath}`);
console.log(entries.map((f) => `  ${f.severity} ${f.id} (${f.category})`).join('\n'));
