#!/usr/bin/env bash
#
# Secret scanning with Gitleaks.
#
# Why Gitleaks in addition to Trivy (which can also scan for secrets):
#   - Gitleaks ships roughly 170 provider-specific rules with entropy checks,
#     against Trivy's smaller built-in set, so it catches materially more real
#     credential formats.
#   - It is the tool whose findings this Action can fully control: its ignore
#     mechanisms can be switched off (see below), which Trivy's inline
#     `trivy:ignore` comments cannot be.
# To avoid paying for both, Trivy's `secret` scanner is *not* enabled by
# default (`trivy-scanners: vuln,misconfig`). Consumers who prefer a single
# tool can set `secret-scan: false` and add `secret` to `trivy-scanners`.
#
# Repository content is attacker-controlled on a pull request, so the three
# ways a committed file could hide a leak are all disabled:
#   --ignore-gitleaks-allow    ignore `gitleaks:allow` comments in code
#   --gitleaks-ignore-path     point at an empty directory, so a committed
#                              `.gitleaksignore` cannot suppress findings
#   --config                   use a generated config that extends the default
#                              ruleset, so a committed `.gitleaks.toml` cannot
#                              replace the rules or add blanket allowlists
# Suppression is still possible, but only through the justified ignore file.
#
# `--redact` is passed so that candidate secrets never reach the job log.

# shellcheck source=scripts/lib/common.sh
source "$(dirname "${BASH_SOURCE[0]}")/lib/common.sh"

readonly SECRETS_TIMEOUT_SECONDS=600
readonly MAX_TARGET_MEGABYTES=20

# Writes a Gitleaks config that keeps the upstream ruleset and adds path
# allowlists for generated directories.
write_gitleaks_config() {
  local target="$1"
  {
    printf '# Generated by keldynai/web-security. Do not edit.\n'
    printf '# The upstream ruleset is kept in full; only paths are allowlisted.\n'
    printf '[extend]\n'
    printf 'useDefault = true\n\n'
    printf '[[allowlists]]\n'
    printf 'description = "Generated, vendored and cache directories"\n'
    printf 'paths = [\n'
    local excluded
    for excluded in "${WEB_SECURITY_EXCLUDED_DIRS[@]}"; do
      # Escape regex metacharacters in directory names (".next" -> "\.next").
      printf '  %s(^|/)%s/%s,\n' "'''" "${excluded//./\\.}" "'''"
    done
    printf ']\n'
  } > "${target}"
}

main() {
  local scan_path="${WEB_SECURITY_SCAN_PATH:?WEB_SECURITY_SCAN_PATH is not set}"

  local bin_dir raw_dir tmp_dir
  bin_dir="$(ws::bin_dir)"
  raw_dir="$(ws::raw_dir)"
  tmp_dir="$(ws::make_temp_dir)"
  # shellcheck disable=SC2064
  trap "rm -rf '${tmp_dir}'" EXIT

  local gitleaks="${bin_dir}/gitleaks"
  if [[ ! -x "${gitleaks}" ]]; then
    printf 'the pinned Gitleaks binary is missing; the install step did not complete.\n' > "${tmp_dir}/error"
    ws::record_status secrets error 1 "${tmp_dir}/error" gitleaks ""
    return 0
  fi

  write_gitleaks_config "${tmp_dir}/gitleaks.toml"
  mkdir -p "${tmp_dir}/no-ignores"

  if [[ -d "${scan_path}/node_modules" ]]; then
    ws::warn "node_modules exists in the scan path. Dependencies are excluded from secret scanning, but running this Action before 'npm ci' keeps the scan fastest."
  fi

  local -a args=(
    dir .
    --config "${tmp_dir}/gitleaks.toml"
    --gitleaks-ignore-path "${tmp_dir}/no-ignores"
    --ignore-gitleaks-allow
    --report-format json
    --report-path "${raw_dir}/gitleaks.json"
    --redact
    --no-banner
    --no-color
    --exit-code 0
    --log-level warn
    --max-target-megabytes "${MAX_TARGET_MEGABYTES}"
  )

  ws::group "Secret scanning (Gitleaks): scanning ${scan_path}"

  local exit_code=0
  (
    cd "${scan_path}" || exit 3
    ws::with_timeout "${SECRETS_TIMEOUT_SECONDS}" "${gitleaks}" "${args[@]}"
  ) > "${tmp_dir}/stdout" 2> "${tmp_dir}/stderr" || exit_code=$?

  cat "${tmp_dir}/stdout"
  tail -n 40 "${tmp_dir}/stderr" >&2 || true
  ws::endgroup

  if [[ "${exit_code}" -ne 0 ]]; then
    if [[ "${exit_code}" -eq 124 || "${exit_code}" -eq 137 ]]; then
      printf 'Gitleaks timed out after %s seconds.\n' "${SECRETS_TIMEOUT_SECONDS}" > "${tmp_dir}/error"
    else
      printf 'Gitleaks exited with status %s.\n' "${exit_code}" > "${tmp_dir}/error"
      tail -n 12 "${tmp_dir}/stderr" >> "${tmp_dir}/error" 2>/dev/null || true
    fi
    ws::record_status secrets error "${exit_code}" "${tmp_dir}/error" gitleaks ""
    return 0
  fi

  # Gitleaks omits the report file entirely when there is nothing to report,
  # which the aggregation step treats as "clean" for this scanner only.
  ws::record_status secrets ok 0 "" gitleaks ""
}

main "$@"
