/**
 * Fixture helpers.
 *
 * Repository fixtures are materialised into temporary directories at test time
 * instead of being committed. Committing real `package-lock.json` /
 * `yarn.lock` files would make this repository look like several broken
 * JavaScript projects to its own scanners, and the Action scans itself in CI.
 */

import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

const createdDirectories = [];

/**
 * Writes a nested `{ name: contents | subtree }` specification to a fresh
 * temporary directory and returns its path.
 */
export function createTree(spec, { prefix = 'web-security-test-' } = {}) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), prefix));
  createdDirectories.push(root);
  writeSpec(root, spec);
  return root;
}

function writeSpec(directory, spec) {
  for (const [name, value] of Object.entries(spec)) {
    const target = path.join(directory, name);
    if (typeof value === 'string') {
      fs.mkdirSync(path.dirname(target), { recursive: true });
      fs.writeFileSync(target, value, 'utf8');
    } else {
      fs.mkdirSync(target, { recursive: true });
      writeSpec(target, value);
    }
  }
}

export function cleanupTrees() {
  for (const directory of createdDirectories.splice(0)) {
    fs.rmSync(directory, { recursive: true, force: true });
  }
}

/**
 * Environment for a spawned script: the ambient environment with every
 * Action-related variable removed, plus the given overrides.
 *
 * A contributor who has exported WEB_SECURITY_INPUT_* or GITHUB_* while
 * debugging the Action by hand would otherwise see spurious failures, because
 * the inputs under test are read from the environment.
 */
export function scriptEnv(overrides = {}) {
  const env = {};
  for (const [key, value] of Object.entries(process.env)) {
    if (key.startsWith('WEB_SECURITY_') || key.startsWith('GITHUB_')) continue;
    env[key] = value;
  }
  return { ...env, ...overrides };
}

process.on('exit', cleanupTrees);

// --------------------------------------------------------------------------
// Realistic lockfile headers, which is what package-manager detection reads.
// --------------------------------------------------------------------------

export const NPM_LOCK = JSON.stringify(
  { name: 'fixture', version: '1.0.0', lockfileVersion: 3, requires: true, packages: {} },
  null,
  2,
);

export const YARN_CLASSIC_LOCK = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


lodash@^4.17.0:
  version "4.17.20"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.20.tgz"
`;

export const YARN_BERRY_LOCK = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 8
  cacheKey: 10c0
`;

export const PNPM_LOCK = `lockfileVersion: '9.0'

settings:
  autoInstallPeers: true
`;

export function packageJson(extra = {}) {
  return JSON.stringify({ name: 'fixture', version: '1.0.0', private: true, ...extra }, null, 2);
}

/** A minimal but valid Kubernetes manifest, for the content sniff. */
export const K8S_MANIFEST = `apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
`;
